name: Run Cypress E2E Tests

on: [push]
env:
  CYPRESS_APP_CHECK_TOKEN: ${{secrets.APP_CHECK_TOKEN}}
  CYPRESS_PREMIUM_USER_PASSWORD: ${{secrets.PREMIUM_USER_PASSWORD}}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Start app and tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          browser: chrome
          start: npm run start:test
          wait-on: 'http://[::1]:4200'
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
