name: Run Cypress E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          build_functions: cd functions && npm run install && npm run build
          build: npm run build
          start: npm run start:emulator
          wait-on: http://localhost:6001
        env:
          CYPRESS_APP_CHECK_TOKEN: ${{secrets.APP_CHECK_TOKEN}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_CI_TOKEN}}