name: Run Cypress E2E Tests

on: [push]
env:
  CYPRESS_APP_CHECK_TOKEN: ${{secrets.APP_CHECK_TOKEN}}
  FIREBASE_TOKEN: ${{secrets.FIREBASE_CI_TOKEN}}
  FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Cache emulator
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/**') }}
        continue-on-error: true
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - run: cd functions && npm ci && npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          browser: electron
          build: npm run build:dev
          start: npm run start:emulator
          wait-on: 'http://localhost:4000'
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos